<a href="https://colab.research.google.com/github/jbranca2011-creator/dsrp_2/blob/main/Research_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

My question for the project: Does location have an affect on how much the cost for college is?

In [28]:
import csv
import pandas as pd

In [34]:
college_csv= "/content/College_Scorecard_Cleaned.csv"
college_df= pd.read_csv(college_csv)
college_df.head()

,UNITID,INSTNM,STABBR,REGION,LOCALE,CONTROL,ADM_RATE,SAT_AVG,ACTCMMID,UGDS,COSTT4_A,TUITIONFEE_IN,TUITIONFEE_OUT,PCTPELL,PCTFLOAN,RET_FT4,C150_4,GRAD_DEBT_MDN,MD_EARN_WNE_4YR,MD_EARN_WNE_P10
0,100654,Alabama A & M University,AL,5,12.0,1,0.5795,938.0,18.0,6124.0,27153.0,10024.0,18634.0,0.6298,0.7454,0.6989,0.2403,31000.0,54018.0,40628.0
1,100663,University of Alabama at Birmingham,AL,5,12.0,1,0.8818,1258.0,27.0,11635.0,28145.0,9098.0,22562.0,0.3402,0.4027,0.8009,0.6423,22300.0,64969.0,54501.0
2,100690,Amridge University,AL,5,12.0,2,NaN,NaN,NaN,241.0,NaN,7590.0,7590.0,0.7655,0.8097,NaN,1.0000,32189.0,50075.0,37621.0
3,100706,University of Alabama in Huntsville,AL,5,12.0,1,0.6857,1319.0,28.0,6591.0,27392.0,12132.0,26408.0,0.2464,0.3255,0.8425,0.6429,20705.0,81045.0,61767.0
4,100724,Alabama State University,AL,5,12.0,1,0.9755,976.0,18.0,3477.0,23586.0,11248.0,19576.0,0.7134,0.7420,0.6975,0.3034,31000.0,45998.0,34502.0

In [35]:
college_df

,UNITID,INSTNM,STABBR,REGION,LOCALE,CONTROL,ADM_RATE,SAT_AVG,ACTCMMID,UGDS,COSTT4_A,TUITIONFEE_IN,TUITIONFEE_OUT,PCTPELL,PCTFLOAN,RET_FT4,C150_4,GRAD_DEBT_MDN,MD_EARN_WNE_4YR,MD_EARN_WNE_P10
0,100654,Alabama A & M University,AL,5,12.0,1,0.5795,938.0,18.0,6124.0,27153.0,10024.0,18634.0,0.6298,0.7454,0.6989,0.2403,31000.0,54018.0,40628.0
1,100663,University of Alabama at Birmingham,AL,5,12.0,1,0.8818,1258.0,27.0,11635.0,28145.0,9098.0,22562.0,0.3402,0.4027,0.8009,0.6423,22300.0,64969.0,54501.0
2,100690,Amridge University,AL,5,12.0,2,NaN,NaN,NaN,241.0,NaN,7590.0,7590.0,0.7655,0.8097,NaN,1.0000,32189.0,50075.0,37621.0
3,100706,University of Alabama in Huntsville,AL,5,12.0,1,0.6857,1319.0,28.0,6591.0,27392.0,12132.0,26408.0,0.2464,0.3255,0.8425,0.6429,20705.0,81045.0,61767.0
4,100724,Alabama State University,AL,5,12.0,1,0.9755,976.0,18.0,3477.0,23586.0,11248.0,19576.0,0.7134,0.7420,0.6975,0.3034,31000.0,45998.0,34502.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1515,487524,Husson University,ME,1,13.0,2,0.8095,1180.0,NaN,2618.0,35852.0,23304.0,23304.0,0.3881,0.7168,0.7535,0.5935,27000.0,62950.0,45025.0
1516,489937,Carolina University,NC,5,11.0,2,0.3954,NaN,NaN,460.0,32680.0,17575.0,17575.0,0.3726,0.4458,0.5636,0.2155,20287.0,52812.0,32864.0
1517,490805,Purdue University Northwest,IN,3,21.0,1,0.7236,1024.0,23.0,5671.0,15571.0,8675.0,16094.0,0.2806,0.2532,0.6570,0.4291,21229.0,73337.0,48318.0
1518,498562,Commonwealth University of Pennsylvania,PA,2,32.0,1,0.9309,1090.0,NaN,9210.0,25161.0,11046.0,22870.0,0.3179,0.5394,0.7757,0.5448,26000.0,58676.0,52416.0
1519,498571,Pennsylvania Western University,PA,2,32.0,1,0.9433,1063.0,NaN,7451.0,26916.0,11436.0,16054.0,0.3830,0.5978,0.7169,0.5188,23725.0,54553.0,47295.0

In [36]:
college_df.shape

(1520, 20)

In [37]:
college_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1520 entries, 0 to 1519
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   UNITID           1520 non-null   int64
 1   INSTNM           1520 non-null   object
 2   STABBR           1520 non-null   object
 3   REGION           1520 non-null   int64
 4   LOCALE           1520 non-null   float64
 5   CONTROL          1520 non-null   int64
 6   ADM_RATE         1383 non-null   float64
 7   SAT_AVG          948 non-null    float64
 8   ACTCMMID         915 non-null    float64
 9   UGDS             1520 non-null   float64
 10  COSTT4_A         1506 non-null   float64
 11  TUITIONFEE_IN    1520 non-null   float64
 12  TUITIONFEE_OUT   1520 non-null   float64
 13  PCTPELL          1520 non-null   float64
 14  PCTFLOAN         1520 non-null   float64
 15  RET_FT4          1509 non-null   float64
 16  C150_4           1511 non-null   float64
 17  GRAD_DEBT_MDN    1520 non-null   float64
 18  MD_EARN_WNE_4YR  1500 non-null   float64
 19  MD_EARN_WNE_P10  1520 non-null   float64
dtypes: float64(15), int64(3), object(2)
memory usage: 237.6+ KB

In [59]:
college_df_cleaned = college_df.drop_duplicates().dropna(axis=0, how='any')
college_df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 762 entries, 0 to 1517
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   UNITID           762 non-null    int64
 1   INSTNM           762 non-null    object
 2   STABBR           762 non-null    object
 3   REGION           762 non-null    int64
 4   LOCALE           762 non-null    float64
 5   CONTROL          762 non-null    int64
 6   ADM_RATE         762 non-null    float64
 7   SAT_AVG          762 non-null    float64
 8   ACTCMMID         762 non-null    float64
 9   UGDS             762 non-null    float64
 10  COSTT4_A         762 non-null    float64
 11  TUITIONFEE_IN    762 non-null    float64
 12  TUITIONFEE_OUT   762 non-null    float64
 13  PCTPELL          762 non-null    float64
 14  PCTFLOAN         762 non-null    float64
 15  RET_FT4          762 non-null    float64
 16  C150_4           762 non-null    float64
 17  GRAD_DEBT_MDN    762 non-null    float64
 18  MD_EARN_WNE_4YR  762 non-null    float64
 19  MD_EARN_WNE_P10  762 non-null    float64
dtypes: float64(15), int64(3), object(2)
memory usage: 125.0+ KB

In [56]:
college_df.isna().sum()

UNITID               0
INSTNM               0
STABBR               0
REGION               0
LOCALE               0
CONTROL              0
ADM_RATE           137
SAT_AVG            572
ACTCMMID           605
UGDS                 0
COSTT4_A            14
TUITIONFEE_IN        0
TUITIONFEE_OUT       0
PCTPELL              0
PCTFLOAN             0
RET_FT4             11
C150_4               9
GRAD_DEBT_MDN        0
MD_EARN_WNE_4YR     20
MD_EARN_WNE_P10      0
dtype: int64